name: design_system
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  commons:
    path: ../commons
  core:
    path: ../core
  flutter_svg: ^2.0.14
  dropdown_button2: ^2.3.9
  google_fonts: ^6.2.1
  flutter_multi_formatter: ^2.13.0
  vibration: ^2.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
